#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Downloading cjdns binary..." --weight=1
cd $data_dir
wget https://github.com/dkoukoul/cjdns/releases/download/debian/cjdroute

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Generating cjdroute configuration file..." --weight=1

chmod +x cjdroute
./cjdroute --genconf | ./cjdroute --cleanconf > cjdroute.conf 
echo "Cjdroute configuration file generated"
### echo "Generating seed..."
### echo "/data/cjdroute.conf|$PKTEER_SECRET" | sha256sum | /server/cjdns/cjdroute --genconf-seed
echo "Editing cjdroute configuration file..."
jq '.security[0].setuser = 0' $data_dir/cjdroute.conf > $data_dir/cjdroute.conf.tmp && mv $data_dir/cjdroute.conf.tmp $data_dir/cjdroute.conf
jq '.noBackground = 1' $data_dir/cjdroute.conf > $data_dir/cjdroute.conf.tmp && mv $data_dir/cjdroute.conf.tmp $data_dir/cjdroute.conf

# Use logrotate to manage application logfile(s)
# ynh_use_logrotate

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring cjdns systemd service..."

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating cjdns service in YunoHost..."

yunohost service add $app --description="$app service"

#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Launching cjdns service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" 

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
